import type { ChecklistRequest } from "../schemas/checklist";

export type ChecklistItemTemplate = {
  id: string;
  category: string;
  title: string;
  regulatory_reference: string;
  required: boolean;
  estimated_time_days: number;
  estimated_cost_eur: number;
  dependencies: string[];
  auros_tip: string;
};

const BASE_ITEMS: ChecklistItemTemplate[] = [
  {
    id: "entity-incorporation",
    category: "legal_structure",
    title: "Incorporate issuing SPV or fund vehicle",
    regulatory_reference: "MiCA Art. 4–6 — issuer identification",
    required: true,
    estimated_time_days: 21,
    estimated_cost_eur: 8_000,
    dependencies: [],
    auros_tip: "Match vehicle type to target investor profile before token design.",
  },
  {
    id: "beneficial-owners",
    category: "legal_structure",
    title: "Document UBO register and governance",
    regulatory_reference: "AMLD6 / local corporate law",
    required: true,
    estimated_time_days: 7,
    estimated_cost_eur: 2_500,
    dependencies: ["entity-incorporation"],
    auros_tip: "Keep UBO chain aligned with on-chain ownership mapping.",
  },
  {
    id: "asset-title",
    category: "asset_custody",
    title: "Verify legal title to underlying asset",
    regulatory_reference: "Civil law / land registry",
    required: true,
    estimated_time_days: 14,
    estimated_cost_eur: 3_000,
    dependencies: [],
    auros_tip: "Title opinion should name the SPV as acquirer or lessee.",
  },
  {
    id: "valuation",
    category: "asset_custody",
    title: "Independent valuation report",
    regulatory_reference: "MiCA whitepaper — asset description",
    required: true,
    estimated_time_days: 10,
    estimated_cost_eur: 4_500,
    dependencies: ["asset-title"],
    auros_tip: "Use RICS or equivalent for institutional credibility.",
  },
  {
    id: "kyc-policy",
    category: "kyc_aml",
    title: "Draft KYC/AML policy and CDD procedures",
    regulatory_reference: "AMLD5 / local AML act",
    required: true,
    estimated_time_days: 14,
    estimated_cost_eur: 5_000,
    dependencies: ["entity-incorporation"],
    auros_tip: "Tier CDD for retail; simplified for professional investors only if eligible.",
  },
  {
    id: "aml-officer",
    category: "kyc_aml",
    title: "Appoint AML compliance officer",
    regulatory_reference: "National AML supervisor guidance",
    required: true,
    estimated_time_days: 7,
    estimated_cost_eur: 3_500,
    dependencies: ["kyc-policy"],
    auros_tip: "Outsource to regulated EMI/CASP partner if no in-house capacity.",
  },
  {
    id: "sanctions-screening",
    category: "kyc_aml",
    title: "Implement sanctions and PEP screening",
    regulatory_reference: "FATF Recommendation 10",
    required: true,
    estimated_time_days: 5,
    estimated_cost_eur: 1_200,
    dependencies: ["kyc-policy"],
    auros_tip: "Automate re-screening on redemption events.",
  },
  {
    id: "mica-classification",
    category: "mica_compliance",
    title: "MiCA asset classification memo",
    regulatory_reference: "MiCA Art. 3 — definitions",
    required: true,
    estimated_time_days: 10,
    estimated_cost_eur: 6_000,
    dependencies: ["entity-incorporation"],
    auros_tip: "Clarify financial instrument vs crypto-asset boundary early.",
  },
  {
    id: "whitepaper",
    category: "mica_compliance",
    title: "Draft crypto-asset whitepaper or prospectus",
    regulatory_reference: "MiCA Art. 6–14 / Prospectus Regulation",
    required: true,
    estimated_time_days: 21,
    estimated_cost_eur: 12_000,
    dependencies: ["mica-classification", "valuation"],
    auros_tip: "Retail distribution requires finalized whitepaper before marketing.",
  },
  {
    id: "eu-nexus-analysis",
    category: "mica_compliance",
    title: "EU nexus and passporting analysis",
    regulatory_reference: "MiCA territorial scope",
    required: true,
    estimated_time_days: 7,
    estimated_cost_eur: 4_000,
    dependencies: ["mica-classification"],
    auros_tip: "Map issuer, asset location, and investor geography separately.",
  },
  {
    id: "data-room-index",
    category: "data_room",
    title: "Structure investor data room index",
    regulatory_reference: "Best practice / institutional DD",
    required: true,
    estimated_time_days: 5,
    estimated_cost_eur: 1_500,
    dependencies: ["asset-title", "valuation"],
    auros_tip: "Version documents — investors expect dated legal opinions.",
  },
  {
    id: "custody-agreement",
    category: "asset_custody",
    title: "Custody or escrow agreement for asset",
    regulatory_reference: "MiCA custody requirements (if applicable)",
    required: true,
    estimated_time_days: 14,
    estimated_cost_eur: 5_500,
    dependencies: ["asset-title"],
    auros_tip: "Separate legal custody from token custody wallet.",
  },
  {
    id: "smart-contract-audit",
    category: "technology",
    title: "Smart contract security audit",
    regulatory_reference: "Industry standard — MiCA operational resilience",
    required: false,
    estimated_time_days: 14,
    estimated_cost_eur: 15_000,
    dependencies: ["token-spec"],
    auros_tip: "ERC-3643/T-REX patterns help institutional acceptance.",
  },
  {
    id: "token-spec",
    category: "technology",
    title: "Token economics and transfer restriction spec",
    regulatory_reference: "MiCA Art. 4 — rights and obligations",
    required: true,
    estimated_time_days: 10,
    estimated_cost_eur: 4_000,
    dependencies: ["whitepaper"],
    auros_tip: "Define lock-up, dividend waterfall, and redemption triggers.",
  },
  {
    id: "investor-agreement",
    category: "investor_protection",
    title: "Subscription and investor agreement template",
    regulatory_reference: "National securities / contract law",
    required: true,
    estimated_time_days: 10,
    estimated_cost_eur: 5_000,
    dependencies: ["whitepaper"],
    auros_tip: "Plain-language summary mandatory for retail channels.",
  },
  {
    id: "risk-disclosures",
    category: "investor_protection",
    title: "Risk factor disclosures",
    regulatory_reference: "MiCA Art. 6(5) — risk section",
    required: true,
    estimated_time_days: 7,
    estimated_cost_eur: 3_000,
    dependencies: ["whitepaper"],
    auros_tip: "Include liquidity, regulatory, and oracle risks explicitly.",
  },
  {
    id: "marketing-review",
    category: "investor_protection",
    title: "Marketing materials compliance review",
    regulatory_reference: "MiCA Art. 68 — marketing communications",
    required: true,
    estimated_time_days: 5,
    estimated_cost_eur: 2_500,
    dependencies: ["whitepaper", "risk-disclosures"],
    auros_tip: "No performance promises without verified track record.",
  },
  {
    id: "tax-memo",
    category: "tax",
    title: "Cross-border tax structuring memo",
    regulatory_reference: "OECD / local tax code",
    required: false,
    estimated_time_days: 14,
    estimated_cost_eur: 7_500,
    dependencies: ["entity-incorporation"],
    auros_tip: "Withholding on distributions varies sharply by investor domicile.",
  },
  {
    id: "insurance",
    category: "risk",
    title: "D&O and asset insurance review",
    regulatory_reference: "Institutional investor expectations",
    required: false,
    estimated_time_days: 7,
    estimated_cost_eur: 4_000,
    dependencies: ["asset-title"],
    auros_tip: "Required by many LPs for real assets above €5M.",
  },
  {
    id: "regulatory-notification",
    category: "mica_compliance",
    title: "Competent authority notification (if required)",
    regulatory_reference: "MiCA CASP / financial instrument rules",
    required: false,
    estimated_time_days: 21,
    estimated_cost_eur: 6_500,
    dependencies: ["mica-classification", "whitepaper"],
    auros_tip: "CSSF/FINMA timelines differ — plan buffer before launch.",
  },
  {
    id: "oracle-data",
    category: "technology",
    title: "NAV / valuation oracle and reporting cadence",
    regulatory_reference: "Operational resilience / investor reporting",
    required: true,
    estimated_time_days: 10,
    estimated_cost_eur: 3_500,
    dependencies: ["valuation", "token-spec"],
    auros_tip: "Quarterly NAV updates are baseline for fund-style products.",
  },
  {
    id: "complaint-handling",
    category: "investor_protection",
    title: "Investor complaint handling procedure",
    regulatory_reference: "MiFID / national conduct rules (if applicable)",
    required: true,
    estimated_time_days: 5,
    estimated_cost_eur: 1_800,
    dependencies: ["investor-agreement"],
    auros_tip: "Document SLA — regulators ask for logs on retail products.",
  },
];

const REAL_ESTATE_EXTRA: ChecklistItemTemplate[] = [
  {
    id: "lease-review",
    category: "asset_custody",
    title: "Review tenant leases and occupancy",
    regulatory_reference: "Property law / revenue underwriting",
    required: true,
    estimated_time_days: 10,
    estimated_cost_eur: 2_800,
    dependencies: ["asset-title"],
    auros_tip: "Retail or warehouse income drives token yield narrative.",
  },
  {
    id: "building-compliance",
    category: "asset_custody",
    title: "Building permits and energy compliance",
    regulatory_reference: "Local planning / CSRD adjacency",
    required: true,
    estimated_time_days: 14,
    estimated_cost_eur: 3_200,
    dependencies: ["asset-title"],
    auros_tip: "EPC ratings increasingly requested by EU institutional LPs.",
  },
  {
    id: "property-insurance",
    category: "risk",
    title: "Property all-risk insurance certificate",
    regulatory_reference: "Lender / investor covenant",
    required: true,
    estimated_time_days: 7,
    estimated_cost_eur: 2_000,
    dependencies: ["asset-title"],
    auros_tip: "Name SPV as loss payee before token issuance.",
  },
];

const PRIVATE_FUND_EXTRA: ChecklistItemTemplate[] = [
  {
    id: "fund-rulebook",
    category: "legal_structure",
    title: "Draft fund rulebook / LPA",
    regulatory_reference: "AIFMD / national fund law",
    required: true,
    estimated_time_days: 28,
    estimated_cost_eur: 18_000,
    dependencies: ["entity-incorporation"],
    auros_tip: "RAIF/SICAV templates accelerate EU institutional onboarding.",
  },
  {
    id: "depositary",
    category: "asset_custody",
    title: "Appoint depositary or administrator",
    regulatory_reference: "AIFMD Art. 21",
    required: true,
    estimated_time_days: 21,
    estimated_cost_eur: 12_000,
    dependencies: ["fund-rulebook"],
    auros_tip: "Luxembourg depositary network is mature for tokenized funds.",
  },
  {
    id: "ppm",
    category: "mica_compliance",
    title: "Private placement memorandum",
    regulatory_reference: "National securities exemptions",
    required: true,
    estimated_time_days: 21,
    estimated_cost_eur: 10_000,
    dependencies: ["fund-rulebook", "mica-classification"],
    auros_tip: "Professional-only exemptions still need full risk disclosure.",
  },
  {
    id: "side-letter",
    category: "investor_protection",
    title: "Side letter template for anchor LPs",
    regulatory_reference: "Contract law",
    required: false,
    estimated_time_days: 7,
    estimated_cost_eur: 4_500,
    dependencies: ["ppm"],
    auros_tip: "Keep side letters consistent with token transfer restrictions.",
  },
];

export function getChecklistTemplates(
  input: ChecklistRequest
): ChecklistItemTemplate[] {
  const items = [...BASE_ITEMS];
  if (input.asset_type === "real_estate") {
    items.push(...REAL_ESTATE_EXTRA);
  } else if (input.asset_type === "private_fund") {
    items.push(...PRIVATE_FUND_EXTRA);
  } else if (input.asset_type === "bonds") {
    items.push({
      id: "bond-indenture",
      category: "legal_structure",
      title: "Bond indenture or note purchase agreement",
      regulatory_reference: "Prospectus / private placement rules",
      required: true,
      estimated_time_days: 21,
      estimated_cost_eur: 9_000,
      dependencies: ["entity-incorporation"],
      auros_tip: "Define coupon, seniority, and default triggers before tokenization.",
    });
  } else if (input.asset_type === "private_credit") {
    items.push({
      id: "loan-tape",
      category: "asset_custody",
      title: "Loan tape due diligence and servicing agreement",
      regulatory_reference: "Credit fund / securitization norms",
      required: true,
      estimated_time_days: 14,
      estimated_cost_eur: 7_000,
      dependencies: ["asset-title"],
      auros_tip: "Vintage and default history must match marketing APY claims.",
    });
  } else if (input.asset_type === "low_carbon_power") {
    items.push(
      {
        id: "generation-source-claim",
        category: "asset_custody",
        title: "Document generation_source technology claim (indicative)",
        regulatory_reference: "AUROS Power / Watts — not GO/REC",
        required: true,
        estimated_time_days: 5,
        estimated_cost_eur: 1_500,
        dependencies: ["asset-title"],
        auros_tip:
          "Use solar|wind|hydro|nuclear|… on Watts/CFU. Outside Green Verified renewables.",
      },
      {
        id: "low-carbon-disclaimer",
        category: "mica_compliance",
        title: "Low-carbon vs renewable marketing disclaimer",
        regulatory_reference: "Anti-greenwashing / EU Taxonomy narrative",
        required: true,
        estimated_time_days: 3,
        estimated_cost_eur: 2_000,
        dependencies: ["mica-classification"],
        auros_tip:
          "Do not apply AUROS Green Verified to nuclear. Hub: /power.",
      },
      {
        id: "cfu-portfolio-pack",
        category: "data_room",
        title: "CFU portfolio export pack for institutional review",
        regulatory_reference: "GET /api/v1/chargeflow/export",
        required: false,
        estimated_time_days: 2,
        estimated_cost_eur: 500,
        dependencies: ["generation-source-claim"],
        auros_tip: "Premium export JSON/CSV — indicative, not a regulated audit opinion.",
      }
    );
  }

  return items.map((item) => ({
    ...item,
    auros_tip: `${item.auros_tip} (jurisdiction: ${input.jurisdiction})`,
  }));
}
