import { completeAiText } from "@/lib/ai-router";
import { listProtocolProducts } from "@/lib/protocol/products/adapter";

import { insertCopilotDraft } from "./drafts-store";
import type { CopilotDraft } from "./types";

/**
 * Scan comparator hub products for incomplete fields → catalog drafts (no live write).
 */
export async function runCatalogDraftAgent(options?: {
  limit?: number;
}): Promise<CopilotDraft[]> {
  let products: Awaited<ReturnType<typeof listProtocolProducts>>["products"] =
    [];
  try {
    const listed = await listProtocolProducts({
      category: "all",
      page: 1,
      limit: 100,
      sort: "tvl",
    });
    products = listed.products;
  } catch (err) {
    console.warn("[copilot] catalog agent hub unavailable", err);
    return [];
  }
  const created: CopilotDraft[] = [];
  const max = options?.limit ?? 10;

  for (const p of products) {
    if (created.length >= max) break;
    const gaps: string[] = [];
    if (!p.jurisdiction) gaps.push("jurisdiction");
    if (p.min_investment_usd == null) gaps.push("min_investment_usd");
    if (!p.chains?.length) gaps.push("chains");
    if (!p.live) gaps.push("live_flag_false");
    if (gaps.length === 0) continue;

    const draft = await insertCopilotDraft({
      kind: "catalog",
      title: `Enrich ${p.id} (${p.name})`,
      rationale: `Missing or weak fields on hub product: ${gaps.join(", ")}.`,
      confidence: Math.min(0.9, 0.45 + gaps.length * 0.1),
      product_id: p.id,
      proposed_patch: {
        product_id: p.id,
        name: p.name,
        platform: p.platform,
        category: p.category,
        gaps,
        suggested: {
          jurisdiction: p.jurisdiction ?? "REVIEW_REQUIRED",
          min_investment_usd: p.min_investment_usd ?? "REVIEW_REQUIRED",
          verify_live: !p.live,
        },
        merge_hint:
          "Human review required — do not auto-edit comparator hub without validation.",
      },
    });
    created.push(draft);
  }

  return created;
}

function templateContentBody(
  topic: string,
  hint: "faq" | "listing_blurb" | "changelog",
  productId?: string
): Record<string, unknown> {
  if (hint === "changelog") {
    return {
      title: `Changelog draft: ${topic.slice(0, 80)}`,
      summary: topic,
      details: [
        "Draft generated by AUROS Copilot content agent.",
        "Human must edit before publishing to PROTOCOL_CHANGELOG.",
      ],
    };
  }
  if (hint === "listing_blurb") {
    return {
      product_id: productId ?? null,
      blurb_fr: `Fiche indicative pour ${topic}. À valider (APY/TVL/juridiction).`,
      blurb_en: `Indicative listing blurb for ${topic}. Validate APY/TVL/jurisdiction before publish.`,
    };
  }
  return {
    question: topic,
    answer_fr:
      "Réponse brouillon Copilot — vérifier les faits catalogue et ajouter counsel disclaimer.",
    answer_en:
      "Copilot draft answer — verify catalog facts and keep counsel disclaimer.",
  };
}

function parseJsonObject(raw: string): Record<string, unknown> | null {
  const cleaned = raw
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();
  try {
    const parsed = JSON.parse(cleaned) as unknown;
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>;
    }
  } catch {
    /* ignore */
  }
  return null;
}

/**
 * Propose a content draft (FAQ / listing blurb) from a prompt or catalog context.
 * Uses free/cheap AI when keys are present; otherwise template body.
 */
export async function runContentDraftAgent(input: {
  topic: string;
  product_id?: string;
  kind_hint?: "faq" | "listing_blurb" | "changelog";
}): Promise<CopilotDraft> {
  const topic = input.topic.trim().slice(0, 500);
  const hint = input.kind_hint ?? "faq";
  let body = templateContentBody(topic, hint, input.product_id);
  let confidence = 0.55;
  let aiProvider: string | null = null;

  const schemaHint =
    hint === "faq"
      ? '{ "question": string, "answer_fr": string, "answer_en": string }'
      : hint === "listing_blurb"
        ? '{ "product_id": string|null, "blurb_fr": string, "blurb_en": string }'
        : '{ "title": string, "summary": string, "details": string[] }';

  const enriched = await completeAiText({
    system: `You draft AUROS editorial content for human review.
Output ONLY valid JSON matching: ${schemaHint}
Rules: no invented APY/TVL/licenses; no Tesla/Total partnership claims; FR+EN when both fields exist; institutional tone; keep counsel disclaimer tone.`,
    user: `content_kind=${hint}\ntopic=${topic}\nproduct_id=${input.product_id ?? "null"}`,
    maxTokens: 700,
  });

  if (enriched) {
    const parsed = parseJsonObject(enriched.text);
    if (parsed) {
      body = { ...body, ...parsed };
      confidence = 0.72;
      aiProvider = enriched.provider;
    }
  }

  return insertCopilotDraft({
    kind: "content",
    title: `Content ${hint}: ${topic.slice(0, 72)}`,
    rationale: aiProvider
      ? `Content agent draft (${hint}) via ${aiProvider} — awaiting human approval.`
      : `Content agent draft (${hint}) awaiting human approval.`,
    confidence,
    product_id: input.product_id ?? null,
    proposed_patch: {
      content_kind: hint,
      topic,
      body,
      ai_provider: aiProvider,
      merge_hint: "Approve stores status only; merge into site content is manual.",
    },
  });
}
