import { listProtocolProducts } from "@/lib/protocol/products/adapter";

import { insertCopilotDraft } from "./drafts-store";
import type { CopilotDraft } from "./types";

/**
 * Scan comparator hub products for incomplete fields → catalog drafts (no live write).
 */
export async function runCatalogDraftAgent(options?: {
  limit?: number;
}): Promise<CopilotDraft[]> {
  let products: Awaited<ReturnType<typeof listProtocolProducts>>["products"] =
    [];
  try {
    const listed = await listProtocolProducts({
      category: "all",
      page: 1,
      limit: 100,
      sort: "tvl",
    });
    products = listed.products;
  } catch (err) {
    console.warn("[copilot] catalog agent hub unavailable", err);
    return [];
  }
  const created: CopilotDraft[] = [];
  const max = options?.limit ?? 10;

  for (const p of products) {
    if (created.length >= max) break;
    const gaps: string[] = [];
    if (!p.jurisdiction) gaps.push("jurisdiction");
    if (p.min_investment_usd == null) gaps.push("min_investment_usd");
    if (!p.chains?.length) gaps.push("chains");
    if (!p.live) gaps.push("live_flag_false");
    if (gaps.length === 0) continue;

    const draft = await insertCopilotDraft({
      kind: "catalog",
      title: `Enrich ${p.id} (${p.name})`,
      rationale: `Missing or weak fields on hub product: ${gaps.join(", ")}.`,
      confidence: Math.min(0.9, 0.45 + gaps.length * 0.1),
      product_id: p.id,
      proposed_patch: {
        product_id: p.id,
        name: p.name,
        platform: p.platform,
        category: p.category,
        gaps,
        suggested: {
          jurisdiction: p.jurisdiction ?? "REVIEW_REQUIRED",
          min_investment_usd: p.min_investment_usd ?? "REVIEW_REQUIRED",
          verify_live: !p.live,
        },
        merge_hint:
          "Human review required — do not auto-edit comparator hub without validation.",
      },
    });
    created.push(draft);
  }

  return created;
}

/**
 * Propose a content draft (FAQ / listing blurb) from a prompt or catalog context.
 */
export async function runContentDraftAgent(input: {
  topic: string;
  product_id?: string;
  kind_hint?: "faq" | "listing_blurb" | "changelog";
}): Promise<CopilotDraft> {
  const topic = input.topic.trim().slice(0, 500);
  const hint = input.kind_hint ?? "faq";
  const body =
    hint === "changelog"
      ? {
          title: `Changelog draft: ${topic.slice(0, 80)}`,
          summary: topic,
          details: [
            "Draft generated by AUROS Copilot content agent.",
            "Human must edit before publishing to PROTOCOL_CHANGELOG.",
          ],
        }
      : hint === "listing_blurb"
        ? {
            product_id: input.product_id ?? null,
            blurb_fr: `Fiche indicative pour ${topic}. À valider (APY/TVL/juridiction).`,
            blurb_en: `Indicative listing blurb for ${topic}. Validate APY/TVL/jurisdiction before publish.`,
          }
        : {
            question: topic,
            answer_fr:
              "Réponse brouillon Copilot — vérifier les faits catalogue et ajouter counsel disclaimer.",
            answer_en:
              "Copilot draft answer — verify catalog facts and keep counsel disclaimer.",
          };

  return insertCopilotDraft({
    kind: "content",
    title: `Content ${hint}: ${topic.slice(0, 72)}`,
    rationale: `Content agent draft (${hint}) awaiting human approval.`,
    confidence: 0.55,
    product_id: input.product_id ?? null,
    proposed_patch: {
      content_kind: hint,
      topic,
      body,
      merge_hint: "Approve stores status only; merge into site content is manual.",
    },
  });
}
