import { absoluteUrl } from "@/lib/comparators/site";

export const AUROS_ORG = {
  name: "AUROS",
  legalName: "AUROS",
  url: absoluteUrl("/"),
  logo: absoluteUrl("/favicon.ico"),
  description:
    "Plateforme B2B de tokenisation RWA : comparateur de juridictions, dossier d'admission actif, Starter Kit juridiction, AUROS Green (RTMS), Watts Reserve, ChargeFlow CFU et Protocol API.",
  sameAs: [] as string[],
  contactEmail: "adrien.balitrand@gmail.com",
  areaServed: ["EU", "MENA", "APAC", "CH"],
  knowsAbout: [
    "RWA tokenization",
    "real-world asset tokenization",
    "MiCA",
    "security tokens",
    "SPV structuring",
    "jurisdiction comparison",
    "DIFC",
    "Luxembourg CSSF",
    "VARA Dubai",
    "AUROS Green",
    "RTMS",
    "AUROS Watts",
    "Watts Reserve",
    "ChargeFlow",
    "CFU-E",
    "CFU-F",
    "CFU-W",
    "energy RWA",
    "EV fleet charge verification",
    "hydrological passport",
    "CSRD green reporting",
  ],
} as const;
