import type { Locale } from "@/lib/i18n";

export type PdfStrings = {
  reportTitle: string;
  footer: (date: string) => string;
  sections: {
    asset: string;
    score: string;
    docs: string;
    description: string;
    legal: string;
    ai: string;
    platforms: string;
    smartContract: string;
    nextSteps: string;
  };
  labels: {
    owner: string;
    location: string;
    legalHolding: string;
    value: string;
    cashFlows: string;
    admission: string;
    dataRoom: string;
    completeness: string;
    platform: string;
    mica: string;
    document: string;
    status: string;
    available: string;
    missing: string;
    clearTitle: string;
    noEncumbrance: string;
    taxCompliant: string;
    yes: string;
    no: string;
    yesPlain: string;
    legal: string;
    valuation: string;
    dueDiligence: string;
    match: string;
    tokenStandard: string;
    fractionalizable: string;
    transferRestrictions: string;
    estSupply: string;
    reviewRequired: string;
    euOnly: string;
    global: string;
  };
  goals: Record<string, string>;
  income: {
    rental: (amount: string) => string;
    none: string;
    future: string;
  };
  fallbacks: {
    legalAi: string;
    valuationAi: (amount: string) => string;
    ddAi: string;
    unspecifiedAsset: string;
  };
  steps: {
    gatherDocs: string;
    uploadDocs: string;
    confirmStructure: string;
    alignStructure: (s: string) => string;
    onboarding: (platform: string, profile: string) => string;
  };
  docSubject: string;
  filenamePrefix: string;
};

const FR: PdfStrings = {
  reportTitle: "RAPPORT DE TOKENISATION",
  footer: (date) =>
    `Généré par AUROS · ${date} · Confidentiel. Document indicatif — pas un conseil juridique ou financier.`,
  sections: {
    asset: "A · Identité de l'actif",
    score: "B · Score & préparation",
    docs: "C · État documentaire",
    description: "D · Description",
    legal: "E · Statut juridique",
    ai: "F · Analyse IA",
    platforms: "G · Compatibilité plateformes",
    smartContract: "H · Paramètres jeton (blueprint)",
    nextSteps: "I · Prochaines étapes",
  },
  labels: {
    owner: "Porteur",
    location: "Localisation",
    legalHolding: "Structure",
    value: "Valorisation",
    cashFlows: "Flux",
    admission: "Admission",
    dataRoom: "Data room",
    completeness: "Complétude",
    platform: "Plateforme",
    mica: "MiCA",
    document: "Document",
    status: "Statut",
    available: "Disponible",
    missing: "Manquant",
    clearTitle: "Titre clair",
    noEncumbrance: "Sans charge",
    taxCompliant: "Fiscalité OK",
    yes: "OUI",
    no: "NON",
    yesPlain: "Oui",
    legal: "Juridique",
    valuation: "Valorisation",
    dueDiligence: "Due diligence",
    match: "Match",
    tokenStandard: "Standard jeton",
    fractionalizable: "Fractionnable",
    transferRestrictions: "Restrictions transfert",
    estSupply: "Offre estimée",
    reviewRequired: "À valider",
    euOnly: "UE uniquement",
    global: "Global",
  },
  goals: {
    income: "Revenus passifs",
    liquidity: "Liquidité",
    diversification: "Diversification",
    estate: "Transmission",
  },
  income: {
    rental: (a) => `Location · ${a}/an`,
    none: "Pas de revenus actuels",
    future: "Revenus futurs potentiels",
  },
  fallbacks: {
    legalAi: "Synthèse juridique préliminaire — revue complète à prévoir.",
    valuationAi: (a) => `Déclaratif ${a} — expertise indépendante recommandée.`,
    ddAi: "KYC, titre et conformité juridiction à finaliser.",
    unspecifiedAsset: "Actif non précisé",
  },
  steps: {
    gatherDocs: "Réunir titre de propriété et expertise indépendante.",
    uploadDocs: "Déposer les pièces sur le portail KYC de la plateforme.",
    confirmStructure: "Valider la structure juridique avec un cabinet avant émission.",
    alignStructure: (s) => `Aligner le cap table : ${s}.`,
    onboarding: (p, prof) =>
      `Onboarding ${p} — profil investisseur (${prof}).`,
  },
  docSubject: "Rapport de tokenisation",
  filenamePrefix: "AUROS_Rapport",
};

const EN: PdfStrings = {
  reportTitle: "TOKENIZATION REPORT",
  footer: (date) =>
    `Generated by AUROS · ${date} · Confidential. Informational only — not legal or financial advice.`,
  sections: {
    asset: "A · Asset identity",
    score: "B · Score & readiness",
    docs: "C · Documentation status",
    description: "D · Asset description",
    legal: "E · Legal status",
    ai: "F · AI analysis",
    platforms: "G · Platform compatibility",
    smartContract: "H · Smart contract parameters",
    nextSteps: "I · Next steps",
  },
  labels: {
    owner: "Owner",
    location: "Location",
    legalHolding: "Legal holding",
    value: "Value",
    cashFlows: "Cash flows",
    admission: "Admission",
    dataRoom: "Data room",
    completeness: "Completeness",
    platform: "Platform",
    mica: "MiCA",
    document: "Document",
    status: "Status",
    available: "Available",
    missing: "Missing",
    clearTitle: "Clear title",
    noEncumbrance: "No encumbrance",
    taxCompliant: "Tax compliant",
    yes: "YES",
    no: "NO",
    yesPlain: "Yes",
    legal: "Legal",
    valuation: "Valuation",
    dueDiligence: "Due diligence",
    match: "Match",
    tokenStandard: "Token standard",
    fractionalizable: "Fractionalizable",
    transferRestrictions: "Transfer restrictions",
    estSupply: "Est. token supply",
    reviewRequired: "Review required",
    euOnly: "EU only",
    global: "Global",
  },
  goals: {
    income: "Passive income",
    liquidity: "Liquidity",
    diversification: "Diversification",
    estate: "Estate planning",
  },
  income: {
    rental: (a) => `Rental · ${a}/yr`,
    none: "No current income",
    future: "Potential future income",
  },
  fallbacks: {
    legalAi:
      "Preliminary legal narrative will be generated upon full dossier review.",
    valuationAi: (a) =>
      `Owner-declared ${a} — independent appraisal recommended.`,
    ddAi:
      "Standard KYC, title verification, and jurisdiction compliance checks apply.",
    unspecifiedAsset: "Unspecified asset",
  },
  steps: {
    gatherDocs:
      "Gather title deed and independent valuation for platform submission.",
    uploadDocs:
      "Upload collected documentation to the selected platform KYC portal.",
    confirmStructure:
      "Confirm legal holding structure with counsel before token issuance.",
    alignStructure: (s) => `Align cap table for structure: ${s}.`,
    onboarding: (p, prof) =>
      `Target ${p} onboarding — investor profile (${prof}).`,
  },
  docSubject: "Tokenization report",
  filenamePrefix: "AUROS_Report",
};

const ES: PdfStrings = {
  reportTitle: "INFORME DE TOKENIZACIÓN",
  footer: (date) =>
    `Generado por AUROS · ${date} · Confidencial. Solo informativo — no es asesoramiento legal ni financiero.`,
  sections: {
    asset: "A · Identidad del activo",
    score: "B · Puntuación y preparación",
    docs: "C · Estado documental",
    description: "D · Descripción",
    legal: "E · Estado legal",
    ai: "F · Análisis IA",
    platforms: "G · Compatibilidad plataformas",
    smartContract: "H · Parámetros token (blueprint)",
    nextSteps: "I · Próximos pasos",
  },
  labels: {
    owner: "Titular",
    location: "Ubicación",
    legalHolding: "Estructura",
    value: "Valoración",
    cashFlows: "Flujos",
    admission: "Admisión",
    dataRoom: "Data room",
    completeness: "Completitud",
    platform: "Plataforma",
    mica: "MiCA",
    document: "Documento",
    status: "Estado",
    available: "Disponible",
    missing: "Falta",
    clearTitle: "Título claro",
    noEncumbrance: "Sin cargas",
    taxCompliant: "Fiscal OK",
    yes: "SÍ",
    no: "NO",
    yesPlain: "Sí",
    legal: "Legal",
    valuation: "Valoración",
    dueDiligence: "Due diligence",
    match: "Match",
    tokenStandard: "Estándar token",
    fractionalizable: "Fraccionable",
    transferRestrictions: "Restricciones",
    estSupply: "Oferta est.",
    reviewRequired: "Revisar",
    euOnly: "Solo UE",
    global: "Global",
  },
  goals: {
    income: "Ingresos pasivos",
    liquidity: "Liquidez",
    diversification: "Diversificación",
    estate: "Sucesión",
  },
  income: {
    rental: (a) => `Alquiler · ${a}/año`,
    none: "Sin ingresos actuales",
    future: "Ingresos futuros potenciales",
  },
  fallbacks: {
    legalAi: "Narrativa legal preliminar — revisión completa pendiente.",
    valuationAi: (a) => `Declarado ${a} — tasación independiente recomendada.`,
    ddAi: "KYC, título y cumplimiento jurisdiccional por finalizar.",
    unspecifiedAsset: "Activo no especificado",
  },
  steps: {
    gatherDocs: "Reunir título y tasación independiente.",
    uploadDocs: "Subir documentación al portal KYC de la plataforma.",
    confirmStructure:
      "Validar estructura legal con asesoría antes de la emisión.",
    alignStructure: (s) => `Alinear cap table: ${s}.`,
    onboarding: (p, prof) => `Onboarding ${p} — perfil inversor (${prof}).`,
  },
  docSubject: "Informe de tokenización",
  filenamePrefix: "AUROS_Informe",
};

export function getPdfStrings(locale: Locale): PdfStrings {
  if (locale === "fr") return FR;
  if (locale === "es") return ES;
  return EN;
}

export function pdfDateLocale(locale: Locale): string {
  if (locale === "fr") return "fr-FR";
  if (locale === "es") return "es-ES";
  return "en-GB";
}
