import type { Jurisdiction } from "./types";

export const JURISDICTIONS: Jurisdiction[] = [
  {
    id: "luxembourg",
    feeMinEur: 15_000,
    feeMaxEur: 50_000,
    totalCostMid: 35_000,
    delayMinMonths: 6,
    delayMaxMonths: 12,
    licenseMaxMonths: 9,
    licenseKey: "cssfRaif",
    kycLevel: "strong",
    assetsKey: "immoFundsBonds",
    assetTypes: ["real_estate", "funds", "bonds"],
    taxKey: "zeroPvHolding",
    minInvestorsKey: "none",
    audienceKey: "institutionalEu",
    score: 4.2,
    stabilityLevel: 4,
    stabilityTier: "high",
  },
  {
    id: "dubai-difc",
    feeMinEur: 8_000,
    feeMaxEur: 30_000,
    totalCostMid: 19_000,
    delayMinMonths: 2,
    delayMaxMonths: 4,
    licenseMaxMonths: 3,
    licenseKey: "varaFsra",
    kycLevel: "medium",
    assetsKey: "allAssets",
    assetTypes: ["real_estate", "bonds", "private_credit", "funds"],
    taxKey: "zeroIsPv",
    minInvestorsKey: "none",
    audienceKey: "globalHnwi",
    score: 4.5,
    stabilityLevel: 3,
    stabilityTier: "medium",
    recommended: true,
  },
  {
    id: "singapore",
    feeMinEur: 20_000,
    feeMaxEur: 60_000,
    totalCostMid: 40_000,
    delayMinMonths: 3,
    delayMaxMonths: 6,
    licenseMaxMonths: 5,
    licenseKey: "masCms",
    kycLevel: "strong",
    assetsKey: "immoAsiaReit",
    assetTypes: ["real_estate", "funds"],
    taxKey: "zeroPvIs17",
    minInvestorsKey: "none",
    audienceKey: "asiaPacific",
    score: 4.3,
    stabilityLevel: 5,
    stabilityTier: "high",
  },
  {
    id: "switzerland",
    feeMinEur: 10_000,
    feeMaxEur: 40_000,
    totalCostMid: 25_000,
    delayMinMonths: 3,
    delayMaxMonths: 6,
    licenseMaxMonths: 5,
    licenseKey: "finmaDlt",
    kycLevel: "medium",
    assetsKey: "allAssets",
    assetTypes: ["real_estate", "bonds", "private_credit", "funds"],
    taxKey: "cantonVariable",
    minInvestorsKey: "none",
    audienceKey: "euGlobal",
    score: 4.0,
    stabilityLevel: 5,
    stabilityTier: "high",
  },
  {
    id: "france",
    feeMinEur: 5_000,
    feeMaxEur: 20_000,
    totalCostMid: 12_500,
    delayMinMonths: 4,
    delayMaxMonths: 8,
    licenseMaxMonths: 6,
    licenseKey: "amfPsan",
    kycLevel: "strong",
    assetsKey: "financialSecurities",
    assetTypes: ["bonds", "funds"],
    taxKey: "flatTax30",
    minInvestorsKey: "retailPossible",
    audienceKey: "frEu",
    score: 3.2,
    stabilityLevel: 4,
    stabilityTier: "high",
  },
  {
    id: "ireland",
    feeMinEur: 10_000,
    feeMaxEur: 35_000,
    totalCostMid: 22_500,
    delayMinMonths: 4,
    delayMaxMonths: 8,
    licenseMaxMonths: 6,
    licenseKey: "cbiMica",
    kycLevel: "medium",
    assetsKey: "fundsBonds",
    assetTypes: ["funds", "bonds"],
    taxKey: "is125",
    minInvestorsKey: "none",
    audienceKey: "euPassport",
    score: 3.8,
    stabilityLevel: 4,
    stabilityTier: "high",
  },
  {
    id: "bahrain",
    feeMinEur: 5_000,
    feeMaxEur: 15_000,
    totalCostMid: 10_000,
    delayMinMonths: 2,
    delayMaxMonths: 3,
    licenseMaxMonths: 3,
    licenseKey: "cbb",
    kycLevel: "medium",
    assetsKey: "immoSukuk",
    assetTypes: ["real_estate", "bonds"],
    taxKey: "zeroIs",
    minInvestorsKey: "none",
    audienceKey: "mena",
    score: 3.5,
    stabilityLevel: 3,
    stabilityTier: "medium",
    bestValue: true,
  },
  {
    id: "gibraltar",
    feeMinEur: 5_000,
    feeMaxEur: 20_000,
    totalCostMid: 12_500,
    delayMinMonths: 2,
    delayMaxMonths: 4,
    licenseMaxMonths: 3,
    licenseKey: "gfscDlt",
    kycLevel: "light",
    assetsKey: "tokensSecurity",
    assetTypes: ["bonds", "private_credit", "funds"],
    taxKey: "is10",
    minInvestorsKey: "none",
    audienceKey: "cryptoNative",
    score: 3.3,
    stabilityLevel: 3,
    stabilityTier: "medium",
  },
];
