import type { GreenMarketActor, GreenMarketOffer } from "./types";
import { GLOBAL_DEMO_ACTORS, GLOBAL_DEMO_OFFERS } from "./global-demo-data";

const DEMO_LISTING = "demo" as const;

const FRANCE_MOCK_ACTORS: Omit<GreenMarketActor, "listingTier" | "country">[] = [
  {
    id: "prod-solar-luberon",
    type: "producer",
    name: "Ferme solaire du Luberon",
    lat: 43.8765,
    lon: 5.3951,
    capacityKwh: 420_000,
    pricePerKwh: 0.082,
    energyType: "solar",
    isCertified: true,
    status: "available",
    city: "Cadenet",
    region: "Provence",
    description: "Parc solaire 2,4 MWc — surplus PPA disponible en bloc horaire.",
    contactEmail: "contact@luberon-solar.demo",
  },
  {
    id: "prod-wind-bretagne",
    type: "producer",
    name: "Éolien de la Côte d'Émeraude",
    lat: 48.6501,
    lon: -2.0078,
    capacityKwh: 890_000,
    pricePerKwh: 0.071,
    energyType: "wind",
    isCertified: true,
    status: "available",
    city: "Plérin",
    region: "Bretagne",
    description: "5 turbines — production mesurée SCADA, certificats GO.",
    contactEmail: "ppa@cote-emeraude.demo",
  },
  {
    id: "prod-hydro-alps",
    type: "producer",
    name: "Micro-hydro Vallée de l'Arve",
    lat: 45.9237,
    lon: 6.8694,
    capacityKwh: 125_000,
    pricePerKwh: 0.095,
    energyType: "hydro",
    isCertified: false,
    status: "available",
    city: "Chamonix",
    region: "Auvergne-Rhône-Alpes",
    description: "Centrale run-of-river 800 kW — flux continu hors crue.",
    contactEmail: "hydro.arve@demo",
  },
  {
    id: "prod-solar-beauce",
    type: "producer",
    name: "Agrivoltaïque Beauce Sud",
    lat: 48.0892,
    lon: 1.4856,
    capacityKwh: 310_000,
    pricePerKwh: 0.078,
    energyType: "solar",
    isCertified: false,
    status: "pending",
    city: "Étampes",
    region: "Centre-Val de Loire",
    description: "Double usage sol / cultures — candidature Verified en cours.",
    contactEmail: "agri.sol@demo",
  },
  {
    id: "prod-wind-aube",
    type: "producer",
    name: "Parc éolien des Barrois",
    lat: 48.4562,
    lon: 4.8123,
    capacityKwh: 560_000,
    pricePerKwh: 0.069,
    energyType: "wind",
    isCertified: false,
    status: "available",
    city: "Bar-sur-Aube",
    region: "Grand Est",
    description: "Production nocturne dominante — contrat EDF OA expiré 2027.",
    contactEmail: "barrois.wind@demo",
  },
  {
    id: "prod-solar-occitanie",
    type: "producer",
    name: "Toitures solaires Montpellier Métropole",
    lat: 43.6108,
    lon: 3.8767,
    capacityKwh: 95_000,
    pricePerKwh: 0.088,
    energyType: "solar",
    isCertified: true,
    status: "available",
    city: "Montpellier",
    region: "Occitanie",
    description: "Agrégation toitures tertiaires — tokenisation surplus pilote RTMS.",
    contactEmail: "metro.sol@demo",
  },
  {
    id: "prod-hydro-pyrenees",
    type: "producer",
    name: "Hydro Haute-Garonne",
    lat: 42.918,
    lon: 0.618,
    capacityKwh: 210_000,
    pricePerKwh: 0.091,
    energyType: "hydro",
    isCertified: false,
    status: "available",
    city: "Saint-Gaudens",
    region: "Occitanie",
    description: "Petite hydro — débit saisonnier documenté.",
    contactEmail: "haute-garonne.hydro@demo",
  },
  {
    id: "store-battery-lyon",
    type: "storer",
    name: "Battery Hub Lyon Est",
    lat: 45.7485,
    lon: 4.8467,
    capacityKwh: 50_000,
    pricePerKwh: 0.12,
    energyType: "battery",
    isCertified: true,
    status: "available",
    city: "Vénissieux",
    region: "Auvergne-Rhône-Alpes",
    description: "Container BESS 10 MWh — arbitrage et services système.",
    contactEmail: "bess.lyon@demo",
  },
  {
    id: "store-battery-nantes",
    type: "storer",
    name: "Stockage Nantes Atlantique",
    lat: 47.2184,
    lon: -1.5536,
    capacityKwh: 32_000,
    pricePerKwh: 0.115,
    energyType: "battery",
    isCertified: false,
    status: "available",
    city: "Nantes",
    region: "Pays de la Loire",
    description: "Stockage couplé éolien offshore — capacité partagée.",
    contactEmail: "storage.nantes@demo",
  },
  {
    id: "store-battery-toulouse",
    type: "storer",
    name: "Tesla Megapack Toulouse Sud",
    lat: 43.5369,
    lon: 1.494,
    capacityKwh: 80_000,
    pricePerKwh: 0.118,
    energyType: "battery",
    isCertified: true,
    status: "pending",
    city: "Labège",
    region: "Occitanie",
    description: "Mise en service Q3 — pré-réservation capacité.",
    contactEmail: "megapack.tlse@demo",
  },
  {
    id: "store-battery-lille",
    type: "storer",
    name: "Buffer Nord Énergie",
    lat: 50.6292,
    lon: 3.0573,
    capacityKwh: 24_000,
    pricePerKwh: 0.122,
    energyType: "battery",
    isCertified: false,
    status: "available",
    city: "Lille",
    region: "Hauts-de-France",
    description: "Stockage quartier — flexibilité réseau Enedis.",
    contactEmail: "buffer.nord@demo",
  },
  {
    id: "store-battery-bordeaux",
    type: "storer",
    name: "Bordeaux Stockage Vert",
    lat: 44.8378,
    lon: -0.5792,
    capacityKwh: 18_000,
    pricePerKwh: 0.119,
    energyType: "battery",
    isCertified: false,
    status: "available",
    city: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    description: "Second life batteries — traçabilité cycles.",
    contactEmail: "stock.bdx@demo",
  },
  {
    id: "store-battery-strasbourg",
    type: "storer",
    name: "Rhénan Power Buffer",
    lat: 48.5734,
    lon: 7.7521,
    capacityKwh: 40_000,
    pricePerKwh: 0.117,
    energyType: "battery",
    isCertified: true,
    status: "available",
    city: "Strasbourg",
    region: "Grand Est",
    description: "Frontière DE/FR — arbitrage transfrontalier.",
    contactEmail: "rhenan.bess@demo",
  },
  {
    id: "charge-paris-nord",
    type: "charger",
    name: "Hub VE Paris Nord",
    lat: 48.8907,
    lon: 2.3522,
    capacityKwh: 8_500,
    pricePerKwh: 0.35,
    energyType: "mixed",
    isCertified: false,
    status: "available",
    city: "Paris 18e",
    region: "Île-de-France",
    description: "24 bornes DC 150 kW — sourcing vert contractuel.",
    contactEmail: "hub.paris.nord@demo",
  },
  {
    id: "charge-lyon-centre",
    type: "charger",
    name: "Corridor Lyon–Marseille Charge",
    lat: 45.764,
    lon: 4.8357,
    capacityKwh: 12_000,
    pricePerKwh: 0.32,
    energyType: "mixed",
    isCertified: true,
    status: "available",
    city: "Lyon",
    region: "Auvergne-Rhône-Alpes",
    description: "Superchargeurs autoroute — mix solaire + réseau.",
    contactEmail: "corridor.lyon@demo",
  },
  {
    id: "charge-rennes",
    type: "charger",
    name: "Bornes Campus Rennes",
    lat: 48.1173,
    lon: -1.6778,
    capacityKwh: 4_200,
    pricePerKwh: 0.28,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Rennes",
    region: "Bretagne",
    description: "Parking ombrières PV — recharge jour.",
    contactEmail: "campus.ev@demo",
  },
  {
    id: "charge-marseille-port",
    type: "charger",
    name: "Port de Marseille VE Fleet",
    lat: 43.2965,
    lon: 5.3698,
    capacityKwh: 15_000,
    pricePerKwh: 0.31,
    energyType: "mixed",
    isCertified: false,
    status: "pending",
    city: "Marseille",
    region: "Provence",
    description: "Flotte logistique portuaire — extension 2026.",
    contactEmail: "port.ev@demo",
  },
  {
    id: "charge-nancy",
    type: "charger",
    name: "Nancy Mobilité Verte",
    lat: 48.6921,
    lon: 6.1844,
    capacityKwh: 6_800,
    pricePerKwh: 0.29,
    energyType: "wind",
    isCertified: false,
    status: "available",
    city: "Nancy",
    region: "Grand Est",
    description: "PPA éolien dédié flotte municipale.",
    contactEmail: "mobilite.nancy@demo",
  },
  {
    id: "charge-bordeaux",
    type: "charger",
    name: "Bordeaux Euratlantique Charge",
    lat: 44.862,
    lon: -0.551,
    capacityKwh: 9_500,
    pricePerKwh: 0.33,
    energyType: "solar",
    isCertified: true,
    status: "available",
    city: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    description: "Quartier neuf — 100 % ENR certifiée.",
    contactEmail: "euratlantique.ev@demo",
  },
  {
    id: "cons-industrial-dijon",
    type: "consumer",
    name: "Usine agroalimentaire Côte-d'Or",
    lat: 47.322,
    lon: 5.0415,
    capacityKwh: 220_000,
    pricePerKwh: null,
    energyType: "mixed",
    isCertified: false,
    status: "available",
    city: "Dijon",
    region: "Bourgogne",
    description: "Demande baseload — recherche PPA solaire / hydro.",
    contactEmail: "achat.energie@dijon-food.demo",
  },
  {
    id: "cons-campus-saclay",
    type: "consumer",
    name: "Campus Paris-Saclay",
    lat: 48.7136,
    lon: 2.1699,
    capacityKwh: 180_000,
    pricePerKwh: null,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Palaiseau",
    region: "Île-de-France",
    description: "Appel d'offres GO + production locale.",
    contactEmail: "energie@saclay.demo",
  },
  {
    id: "cons-hotel-courchevel",
    type: "consumer",
    name: "Groupe hôtelier Alpes",
    lat: 45.415,
    lon: 6.6347,
    capacityKwh: 45_000,
    pricePerKwh: null,
    energyType: "hydro",
    isCertified: false,
    status: "pending",
    city: "Courchevel",
    region: "Auvergne-Rhône-Alpes",
    description: "Saisonnalité forte — flexibilité stockage recherchée.",
    contactEmail: "ops@alpes-hotels.demo",
  },
  {
    id: "cons-datacenter-reims",
    type: "consumer",
    name: "DC Reims Edge",
    lat: 49.2583,
    lon: 4.0317,
    capacityKwh: 320_000,
    pricePerKwh: null,
    energyType: "wind",
    isCertified: false,
    status: "available",
    city: "Reims",
    region: "Grand Est",
    description: "Charge 24/7 — objectif 80 % renouvelable d'ici 2027.",
    contactEmail: "power@reims-dc.demo",
  },
  {
    id: "cons-cooperative-limoges",
    type: "consumer",
    name: "Coopérative énergie Limousin",
    lat: 45.8336,
    lon: 1.2611,
    capacityKwh: 75_000,
    pricePerKwh: null,
    energyType: "mixed",
    isCertified: true,
    status: "available",
    city: "Limoges",
    region: "Nouvelle-Aquitaine",
    description: "800 membres — achat groupé et autoconsommation.",
    contactEmail: "coop@limousin-energie.demo",
  },
  {
    id: "cons-zac-nantes",
    type: "consumer",
    name: "ZAC Erdre Active",
    lat: 47.256,
    lon: -1.522,
    capacityKwh: 110_000,
    pricePerKwh: null,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Nantes",
    region: "Pays de la Loire",
    description: "Quartier en développement — contrat cadre recherché.",
    contactEmail: "zac.erdre@demo",
  },
];

const MOCK_ACTORS: Omit<GreenMarketActor, "listingTier">[] = [
  ...FRANCE_MOCK_ACTORS.map((a) => ({ ...a, country: "France" })),
  ...GLOBAL_DEMO_ACTORS,
];

export const GREEN_MARKET_ACTORS: GreenMarketActor[] = MOCK_ACTORS.map((a) => ({
  ...a,
  listingTier: DEMO_LISTING,
}));

const FRANCE_MOCK_OFFERS: Omit<GreenMarketOffer, "listingTier" | "country">[] = [
  {
    id: "offer-001",
    actorId: "prod-solar-luberon",
    actorName: "Ferme solaire du Luberon",
    side: "sell",
    volumeKwh: 50_000,
    pricePerKwh: 0.082,
    energyType: "solar",
    lat: 43.8765,
    lon: 5.3951,
    city: "Cadenet",
    createdAt: "2026-05-28T09:00:00Z",
    status: "available",
  },
  {
    id: "offer-002",
    actorId: "prod-wind-bretagne",
    actorName: "Éolien de la Côte d'Émeraude",
    side: "sell",
    volumeKwh: 120_000,
    pricePerKwh: 0.071,
    energyType: "wind",
    lat: 48.6501,
    lon: -2.0078,
    city: "Plérin",
    createdAt: "2026-05-27T14:30:00Z",
    status: "available",
  },
  {
    id: "offer-003",
    actorId: "cons-industrial-dijon",
    actorName: "Usine agroalimentaire Côte-d'Or",
    side: "buy",
    volumeKwh: 80_000,
    pricePerKwh: 0.09,
    energyType: "solar",
    lat: 47.322,
    lon: 5.0415,
    city: "Dijon",
    createdAt: "2026-05-26T11:00:00Z",
    status: "available",
  },
  {
    id: "offer-004",
    actorId: "store-battery-lyon",
    actorName: "Battery Hub Lyon Est",
    side: "sell",
    volumeKwh: 15_000,
    pricePerKwh: 0.12,
    energyType: "battery",
    lat: 45.7485,
    lon: 4.8467,
    city: "Vénissieux",
    createdAt: "2026-05-25T16:45:00Z",
    status: "available",
  },
  {
    id: "offer-005",
    actorId: "cons-datacenter-reims",
    actorName: "DC Reims Edge",
    side: "buy",
    volumeKwh: 200_000,
    pricePerKwh: 0.075,
    energyType: "wind",
    lat: 49.2583,
    lon: 4.0317,
    city: "Reims",
    createdAt: "2026-05-24T08:20:00Z",
    status: "available",
  },
  {
    id: "offer-006",
    actorId: "prod-solar-occitanie",
    actorName: "Toitures solaires Montpellier Métropole",
    side: "sell",
    volumeKwh: 25_000,
    pricePerKwh: 0.088,
    energyType: "solar",
    lat: 43.6108,
    lon: 3.8767,
    city: "Montpellier",
    createdAt: "2026-05-23T10:15:00Z",
    status: "available",
  },
  {
    id: "offer-007",
    actorId: "cons-campus-saclay",
    actorName: "Campus Paris-Saclay",
    side: "buy",
    volumeKwh: 60_000,
    pricePerKwh: 0.085,
    energyType: "solar",
    lat: 48.7136,
    lon: 2.1699,
    city: "Palaiseau",
    createdAt: "2026-05-22T13:00:00Z",
    status: "pending",
  },
  {
    id: "offer-008",
    actorId: "prod-wind-aube",
    actorName: "Parc éolien des Barrois",
    side: "sell",
    volumeKwh: 95_000,
    pricePerKwh: 0.069,
    energyType: "wind",
    lat: 48.4562,
    lon: 4.8123,
    city: "Bar-sur-Aube",
    createdAt: "2026-05-21T07:30:00Z",
    status: "available",
  },
];

const MOCK_OFFERS: Omit<GreenMarketOffer, "listingTier">[] = [
  ...FRANCE_MOCK_OFFERS.map((o) => ({ ...o, country: "France" })),
  ...GLOBAL_DEMO_OFFERS,
];

export const GREEN_MARKET_OFFERS: GreenMarketOffer[] = MOCK_OFFERS.map((o) => ({
  ...o,
  listingTier: DEMO_LISTING,
}));

export function getGreenMarketActorsByType(type: GreenMarketActor["type"]) {
  return GREEN_MARKET_ACTORS.filter((a) => a.type === type);
}

export function getGreenMarketActorById(id: string) {
  return GREEN_MARKET_ACTORS.find((a) => a.id === id);
}
