import type { GreenMarketActor, GreenMarketOffer } from "./types";

/** Worldwide demo actors — mixed with France seed in data.ts */
export const GLOBAL_DEMO_ACTORS: Omit<GreenMarketActor, "listingTier">[] = [
  // — Americas —
  {
    id: "prod-solar-texas",
    type: "producer",
    name: "Lone Star Solar Collective",
    lat: 30.2672,
    lon: -97.7431,
    capacityKwh: 2_400_000,
    pricePerKwh: 0.065,
    energyType: "solar",
    isCertified: true,
    status: "available",
    city: "Austin",
    region: "Texas",
    country: "United States",
    description: "Utility-scale solar — hourly REC blocks and corporate PPA tranches.",
    contactEmail: "ppa@lonestar-solar.demo",
  },
  {
    id: "prod-solar-phoenix",
    type: "producer",
    name: "Sonoran Desert Solar",
    lat: 33.4484,
    lon: -112.074,
    capacityKwh: 1_800_000,
    pricePerKwh: 0.058,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Phoenix",
    region: "Arizona",
    country: "United States",
    description: "Desert PV portfolio — midday surplus and battery-ready export curves.",
    contactEmail: "export@sonoran-solar.demo",
  },
  {
    id: "prod-solar-toronto",
    type: "producer",
    name: "Great Lakes Solar Co-op",
    lat: 43.6532,
    lon: -79.3832,
    capacityKwh: 520_000,
    pricePerKwh: 0.072,
    energyType: "solar",
    isCertified: true,
    status: "available",
    city: "Toronto",
    region: "Ontario",
    country: "Canada",
    description: "Rooftop and ground-mount mix — IESO export data and GO-style attestations.",
    contactEmail: "ppa@greatlakes-solar.demo",
  },
  {
    id: "prod-solar-sao-paulo",
    type: "producer",
    name: "Serra Verde Solar",
    lat: -23.5505,
    lon: -46.6333,
    capacityKwh: 980_000,
    pricePerKwh: 0.048,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "São Paulo",
    region: "SP",
    country: "Brazil",
    description: "Distributed solar fleet — hourly generation for industrial offtake.",
    contactEmail: "vendas@serra-verde.demo",
  },
  {
    id: "charge-mexico-city",
    type: "charger",
    name: "CDMX Metro Charge Hub",
    lat: 19.4326,
    lon: -99.1332,
    capacityKwh: 14_000,
    pricePerKwh: 0.19,
    energyType: "mixed",
    isCertified: false,
    status: "available",
    city: "Mexico City",
    region: "CDMX",
    country: "Mexico",
    description: "Urban DC corridor — green tariff mix and fleet subscription blocks.",
    contactEmail: "flotas@cdmx-charge.demo",
  },
  {
    id: "charge-santiago",
    type: "charger",
    name: "Andes Corridor Charge",
    lat: -33.4489,
    lon: -70.6693,
    capacityKwh: 11_000,
    pricePerKwh: 0.22,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Santiago",
    region: "RM",
    country: "Chile",
    description: "High-altitude DC hub — solar PPA dedicated to fleet operators.",
    contactEmail: "corridor@andes-charge.demo",
  },
  // — Europe (non-FR) —
  {
    id: "prod-wind-scotland",
    type: "producer",
    name: "Highland Offshore Wind",
    lat: 57.4778,
    lon: -4.2247,
    capacityKwh: 1_200_000,
    pricePerKwh: 0.074,
    energyType: "wind",
    isCertified: true,
    status: "available",
    city: "Inverness",
    region: "Highlands",
    country: "United Kingdom",
    description: "Offshore wind farm — GO certificates and metered export data.",
    contactEmail: "export@highland-wind.demo",
  },
  {
    id: "store-battery-berlin",
    type: "storer",
    name: "Berlin Grid Buffer",
    lat: 52.52,
    lon: 13.405,
    capacityKwh: 95_000,
    pricePerKwh: 0.108,
    energyType: "battery",
    isCertified: true,
    status: "available",
    city: "Berlin",
    region: "Berlin",
    country: "Germany",
    description: "BESS container park — intraday arbitrage for industrial offtakers.",
    contactEmail: "bess@berlin-grid.demo",
  },
  {
    id: "prod-hydro-norway",
    type: "producer",
    name: "Fjord Hydro Cooperative",
    lat: 60.3913,
    lon: 5.3221,
    capacityKwh: 780_000,
    pricePerKwh: 0.048,
    energyType: "hydro",
    isCertified: true,
    status: "available",
    city: "Bergen",
    region: "Vestland",
    country: "Norway",
    description: "Run-of-river hydro — 24/7 baseload blocks for Nordic corporates.",
    contactEmail: "sales@fjord-hydro.demo",
  },
  {
    id: "prod-solar-barcelona",
    type: "producer",
    name: "Catalunya Solar Hub",
    lat: 41.3874,
    lon: 2.1686,
    capacityKwh: 640_000,
    pricePerKwh: 0.069,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Barcelona",
    region: "Catalonia",
    country: "Spain",
    description: "Rooftop and carport PV — surplus blocks for local industrial buyers.",
    contactEmail: "surplus@catalunya-solar.demo",
  },
  {
    id: "prod-wind-lombardy",
    type: "producer",
    name: "Po Valley Wind Cluster",
    lat: 45.4642,
    lon: 9.19,
    capacityKwh: 720_000,
    pricePerKwh: 0.076,
    energyType: "wind",
    isCertified: true,
    status: "available",
    city: "Milan",
    region: "Lombardy",
    country: "Italy",
    description: "Onshore wind portfolio — GO-linked export and PPA tranches.",
    contactEmail: "ppa@povalley-wind.demo",
  },
  {
    id: "prod-hydro-algarve",
    type: "producer",
    name: "Algarve Mini-Hydro",
    lat: 37.0179,
    lon: -7.9304,
    capacityKwh: 88_000,
    pricePerKwh: 0.091,
    energyType: "hydro",
    isCertified: false,
    status: "available",
    city: "Faro",
    region: "Algarve",
    country: "Portugal",
    description: "Run-of-river plant — continuous baseload for coastal resorts.",
    contactEmail: "hydro@algarve-mini.demo",
  },
  {
    id: "store-battery-rotterdam",
    type: "storer",
    name: "Harbour BESS Rotterdam",
    lat: 51.9244,
    lon: 4.4777,
    capacityKwh: 110_000,
    pricePerKwh: 0.102,
    energyType: "battery",
    isCertified: true,
    status: "available",
    city: "Rotterdam",
    region: "South Holland",
    country: "Netherlands",
    description: "Port-side battery park — grid services and industrial peak shaving.",
    contactEmail: "bess@harbour-rotterdam.demo",
  },
  {
    id: "cons-industrial-warsaw",
    type: "consumer",
    name: "Mazovia Industrial Park",
    lat: 52.2297,
    lon: 21.0122,
    capacityKwh: 310_000,
    pricePerKwh: null,
    energyType: "wind",
    isCertified: false,
    status: "available",
    city: "Warsaw",
    region: "Mazovia",
    country: "Poland",
    description: "Manufacturing campus — seeking verified wind and solar bundles.",
    contactEmail: "energy@mazovia-park.demo",
  },
  {
    id: "prod-wind-stockholm",
    type: "producer",
    name: "Baltic Wind Export",
    lat: 59.3293,
    lon: 18.0686,
    capacityKwh: 540_000,
    pricePerKwh: 0.055,
    energyType: "wind",
    isCertified: true,
    status: "available",
    city: "Stockholm",
    region: "Stockholm",
    country: "Sweden",
    description: "Nordic wind export — GO certificates and hourly production curves.",
    contactEmail: "export@baltic-wind.demo",
  },
  // — MENA & Africa —
  {
    id: "prod-solar-marrakech",
    type: "producer",
    name: "Atlas Noor Solar",
    lat: 31.6295,
    lon: -7.9811,
    capacityKwh: 650_000,
    pricePerKwh: 0.055,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Marrakech",
    region: "Marrakech-Safi",
    country: "Morocco",
    description: "Noor-linked CSP/solar hybrid — export-ready hourly production curves.",
    contactEmail: "export@atlas-noor.demo",
  },
  {
    id: "store-battery-dubai",
    type: "storer",
    name: "Gulf Peak Storage",
    lat: 25.2048,
    lon: 55.2708,
    capacityKwh: 120_000,
    pricePerKwh: 0.095,
    energyType: "battery",
    isCertified: false,
    status: "available",
    city: "Dubai",
    region: "Dubai",
    country: "United Arab Emirates",
    description: "Desert-cooled BESS — solar coupling and peak shaving for logistics hubs.",
    contactEmail: "storage@gulf-peak.demo",
  },
  {
    id: "prod-solar-riyadh",
    type: "producer",
    name: "Neom Edge Solar",
    lat: 24.7136,
    lon: 46.6753,
    capacityKwh: 1_100_000,
    pricePerKwh: 0.042,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Riyadh",
    region: "Riyadh",
    country: "Saudi Arabia",
    description: "Utility-scale PV — export blocks for regional industrial offtakers.",
    contactEmail: "ppa@neom-edge.demo",
  },
  {
    id: "cons-campus-nairobi",
    type: "consumer",
    name: "East Africa Tech Campus",
    lat: -1.2921,
    lon: 36.8219,
    capacityKwh: 72_000,
    pricePerKwh: null,
    energyType: "solar",
    isCertified: false,
    status: "pending",
    city: "Nairobi",
    region: "Nairobi",
    country: "Kenya",
    description: "Innovation hub — group PPA for rooftop solar and wheeling-ready supply.",
    contactEmail: "energy@east-africa-campus.demo",
  },
  {
    id: "store-battery-lagos",
    type: "storer",
    name: "Lagos Grid Flex",
    lat: 6.5244,
    lon: 3.3792,
    capacityKwh: 65_000,
    pricePerKwh: 0.115,
    energyType: "battery",
    isCertified: false,
    status: "available",
    city: "Lagos",
    region: "Lagos",
    country: "Nigeria",
    description: "Urban BESS — diesel displacement and solar smoothing for industrial sites.",
    contactEmail: "flex@lagos-grid.demo",
  },
  {
    id: "prod-solar-cairo",
    type: "producer",
    name: "Nile Delta Solar",
    lat: 30.0444,
    lon: 31.2357,
    capacityKwh: 480_000,
    pricePerKwh: 0.051,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Cairo",
    region: "Cairo",
    country: "Egypt",
    description: "Desert PV farm — midday export and corporate PPA tranches.",
    contactEmail: "export@nile-delta.demo",
  },
  {
    id: "cons-campus-cape-town",
    type: "consumer",
    name: "Cape Innovation Campus",
    lat: -33.9249,
    lon: 18.4241,
    capacityKwh: 88_000,
    pricePerKwh: null,
    energyType: "solar",
    isCertified: false,
    status: "pending",
    city: "Cape Town",
    region: "Western Cape",
    country: "South Africa",
    description: "Tech park — group PPA for rooftop and wheeling-ready producers.",
    contactEmail: "ppa@cape-campus.demo",
  },
  // — Asia-Pacific —
  {
    id: "charge-singapore",
    type: "charger",
    name: "Marina Bay EV Hub",
    lat: 1.2834,
    lon: 103.8607,
    capacityKwh: 18_000,
    pricePerKwh: 0.28,
    energyType: "mixed",
    isCertified: true,
    status: "available",
    city: "Singapore",
    region: "Central",
    country: "Singapore",
    description: "Ultra-fast corridor — green tariff mix solar + grid import certificates.",
    contactEmail: "fleet@marina-ev.demo",
  },
  {
    id: "cons-industrial-osaka",
    type: "consumer",
    name: "Kansai Manufacturing Cluster",
    lat: 34.6937,
    lon: 135.5023,
    capacityKwh: 540_000,
    pricePerKwh: null,
    energyType: "mixed",
    isCertified: false,
    status: "available",
    city: "Osaka",
    region: "Kansai",
    country: "Japan",
    description: "Industrial baseload — seeking verified solar and storage bundles.",
    contactEmail: "energy@kansai-mfg.demo",
  },
  {
    id: "prod-solar-bangalore",
    type: "producer",
    name: "Deccan Solar Park",
    lat: 12.9716,
    lon: 77.5946,
    capacityKwh: 890_000,
    pricePerKwh: 0.038,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Bangalore",
    region: "Karnataka",
    country: "India",
    description: "Utility-scale PV — corporate PPA and export blocks for IT campuses.",
    contactEmail: "ppa@deccan-solar.demo",
  },
  {
    id: "prod-wind-sydney",
    type: "producer",
    name: "Harbour Wind Cooperative",
    lat: -33.8688,
    lon: 151.2093,
    capacityKwh: 620_000,
    pricePerKwh: 0.068,
    energyType: "wind",
    isCertified: true,
    status: "available",
    city: "Sydney",
    region: "NSW",
    country: "Australia",
    description: "Coastal wind farm — LGC-style attestations and hourly export data.",
    contactEmail: "export@harbour-wind.demo",
  },
  {
    id: "store-battery-seoul",
    type: "storer",
    name: "Gangnam Peak Storage",
    lat: 37.5665,
    lon: 126.978,
    capacityKwh: 78_000,
    pricePerKwh: 0.118,
    energyType: "battery",
    isCertified: true,
    status: "available",
    city: "Seoul",
    region: "Seoul",
    country: "South Korea",
    description: "Urban BESS — demand response and solar coupling for commercial towers.",
    contactEmail: "bess@gangnam-peak.demo",
  },
  {
    id: "cons-industrial-jakarta",
    type: "consumer",
    name: "Java Industrial Estate",
    lat: -6.2088,
    lon: 106.8456,
    capacityKwh: 420_000,
    pricePerKwh: null,
    energyType: "solar",
    isCertified: false,
    status: "available",
    city: "Jakarta",
    region: "Java",
    country: "Indonesia",
    description: "Manufacturing zone — seeking solar imports and storage-as-a-service.",
    contactEmail: "procurement@java-estate.demo",
  },
  {
    id: "charge-bangkok",
    type: "charger",
    name: "Sukhumvit EV Corridor",
    lat: 13.7563,
    lon: 100.5018,
    capacityKwh: 9_500,
    pricePerKwh: 0.24,
    energyType: "mixed",
    isCertified: false,
    status: "available",
    city: "Bangkok",
    region: "Bangkok",
    country: "Thailand",
    description: "Urban fast-charge hub — solar PPA mix for fleet and ride-hail operators.",
    contactEmail: "fleet@sukhumvit-ev.demo",
  },
];

export const GLOBAL_DEMO_OFFERS: Omit<GreenMarketOffer, "listingTier">[] = [
  {
    id: "offer-global-001",
    actorId: "prod-solar-texas",
    actorName: "Lone Star Solar Collective",
    side: "sell",
    volumeKwh: 200_000,
    pricePerKwh: 0.065,
    energyType: "solar",
    lat: 30.2672,
    lon: -97.7431,
    city: "Austin",
    country: "United States",
    createdAt: "2026-05-28T12:00:00Z",
    status: "available",
  },
  {
    id: "offer-global-002",
    actorId: "store-battery-berlin",
    actorName: "Berlin Grid Buffer",
    side: "sell",
    volumeKwh: 40_000,
    pricePerKwh: 0.108,
    energyType: "battery",
    lat: 52.52,
    lon: 13.405,
    city: "Berlin",
    country: "Germany",
    createdAt: "2026-05-27T09:30:00Z",
    status: "available",
  },
  {
    id: "offer-global-003",
    actorId: "cons-industrial-osaka",
    actorName: "Kansai Manufacturing Cluster",
    side: "buy",
    volumeKwh: 150_000,
    pricePerKwh: 0.11,
    energyType: "mixed",
    lat: 34.6937,
    lon: 135.5023,
    city: "Osaka",
    country: "Japan",
    createdAt: "2026-05-26T15:00:00Z",
    status: "available",
  },
  {
    id: "offer-global-004",
    actorId: "prod-wind-scotland",
    actorName: "Highland Offshore Wind",
    side: "sell",
    volumeKwh: 90_000,
    pricePerKwh: 0.074,
    energyType: "wind",
    lat: 57.4778,
    lon: -4.2247,
    city: "Inverness",
    country: "United Kingdom",
    createdAt: "2026-05-25T11:20:00Z",
    status: "available",
  },
  {
    id: "offer-global-005",
    actorId: "store-battery-dubai",
    actorName: "Gulf Peak Storage",
    side: "sell",
    volumeKwh: 25_000,
    pricePerKwh: 0.095,
    energyType: "battery",
    lat: 25.2048,
    lon: 55.2708,
    city: "Dubai",
    country: "United Arab Emirates",
    createdAt: "2026-05-24T08:00:00Z",
    status: "pending",
  },
  {
    id: "offer-global-006",
    actorId: "prod-solar-barcelona",
    actorName: "Catalunya Solar Hub",
    side: "sell",
    volumeKwh: 55_000,
    pricePerKwh: 0.069,
    energyType: "solar",
    lat: 41.3874,
    lon: 2.1686,
    city: "Barcelona",
    country: "Spain",
    createdAt: "2026-05-23T14:00:00Z",
    status: "available",
  },
  {
    id: "offer-global-007",
    actorId: "prod-solar-bangalore",
    actorName: "Deccan Solar Park",
    side: "sell",
    volumeKwh: 120_000,
    pricePerKwh: 0.038,
    energyType: "solar",
    lat: 12.9716,
    lon: 77.5946,
    city: "Bangalore",
    country: "India",
    createdAt: "2026-05-22T10:30:00Z",
    status: "available",
  },
  {
    id: "offer-global-008",
    actorId: "prod-wind-sydney",
    actorName: "Harbour Wind Cooperative",
    side: "sell",
    volumeKwh: 70_000,
    pricePerKwh: 0.068,
    energyType: "wind",
    lat: -33.8688,
    lon: 151.2093,
    city: "Sydney",
    country: "Australia",
    createdAt: "2026-05-21T16:45:00Z",
    status: "available",
  },
  {
    id: "offer-global-009",
    actorId: "prod-solar-toronto",
    actorName: "Great Lakes Solar Co-op",
    side: "sell",
    volumeKwh: 35_000,
    pricePerKwh: 0.072,
    energyType: "solar",
    lat: 43.6532,
    lon: -79.3832,
    city: "Toronto",
    country: "Canada",
    createdAt: "2026-05-20T09:00:00Z",
    status: "available",
  },
  {
    id: "offer-global-010",
    actorId: "cons-industrial-warsaw",
    actorName: "Mazovia Industrial Park",
    side: "buy",
    volumeKwh: 80_000,
    pricePerKwh: 0.085,
    energyType: "wind",
    lat: 52.2297,
    lon: 21.0122,
    city: "Warsaw",
    country: "Poland",
    createdAt: "2026-05-19T11:15:00Z",
    status: "available",
  },
  {
    id: "offer-global-011",
    actorId: "prod-solar-riyadh",
    actorName: "Neom Edge Solar",
    side: "sell",
    volumeKwh: 180_000,
    pricePerKwh: 0.042,
    energyType: "solar",
    lat: 24.7136,
    lon: 46.6753,
    city: "Riyadh",
    country: "Saudi Arabia",
    createdAt: "2026-05-18T07:30:00Z",
    status: "available",
  },
  {
    id: "offer-global-012",
    actorId: "store-battery-seoul",
    actorName: "Gangnam Peak Storage",
    side: "sell",
    volumeKwh: 18_000,
    pricePerKwh: 0.118,
    energyType: "battery",
    lat: 37.5665,
    lon: 126.978,
    city: "Seoul",
    country: "South Korea",
    createdAt: "2026-05-17T13:00:00Z",
    status: "available",
  },
];
